var annotated_dup =
[
    [ "AudioManager", "classAudioManager.html", "classAudioManager" ],
    [ "BaitCard", "classBaitCard.html", null ],
    [ "Board", "classBoard.html", null ],
    [ "BonusCard", "classBonusCard.html", null ],
    [ "ButtonFX", "classButtonFX.html", "classButtonFX" ],
    [ "Card", "classCard.html", "classCard" ],
    [ "CardHoverManager", "classCardHoverManager.html", "classCardHoverManager" ],
    [ "CardManager", "classCardManager.html", null ],
    [ "CardSlot", "classCardSlot.html", null ],
    [ "CardsQuanto", "classCardsQuanto.html", null ],
    [ "ClimateCard", "classClimateCard.html", null ],
    [ "Deck", "classDeck.html", "classDeck" ],
    [ "Effects", "classEffects.html", null ],
    [ "HandPanelManager", "classHandPanelManager.html", "classHandPanelManager" ],
    [ "IEffectRow", "interfaceIEffectRow.html", null ],
    [ "LeaderCard", "classLeaderCard.html", null ],
    [ "Menu", "classMenu.html", "classMenu" ],
    [ "PauseMenu", "classPauseMenu.html", "classPauseMenu" ],
    [ "Player", "classPlayer.html", null ],
    [ "RoundManager", "classRoundManager.html", "classRoundManager" ],
    [ "Tooltip", "classTooltip.html", "classTooltip" ],
    [ "TooltipManager", "classTooltipManager.html", "classTooltipManager" ],
    [ "UnitCard", "classUnitCard.html", null ]
];